---
- name: Instalar node_exporter
  hosts: all
  become: true
  vars:
    node_exporter_install_dir: "/opt/node_exporter"
  tasks:

    - name: Chequeo estado de iptables
      shell: ls -ltr /etc/sysconfig/iptables
      register: iptables_status
      ignore_errors: true
      
    - name: Backup rules
      shell: iptables-save > /etc/sysconfig/iptables.{{ ansible_date_time.date }}
      args:
        warn: no
      register: iptables_backup
      changed_when: iptables_backup.stdout != ""
      when: iptables_status.rc == 0 and ansible_distribution_major_version == '6'

    - name: Obtener IP server
      set_fact:
        server_ip: "{{ ansible_default_ipv4.address }}"
      when: iptables_status.rc == 0
     

    - name: Agrego reglas de entrada desde server prometheus [9100]
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        source: "{{ item }}"
        destination: "{{ server_ip }}"
        destination_port: 9100  
        ctstate: NEW,ESTABLISHED,RELATED
        jump: ACCEPT
        action: insert
        rule_num: 1 
      become: true
      with_items:
        - 172.16.8.64
      when: iptables_status.rc == 0 and ansible_distribution_major_version == '6'

    - name: Agrego reglas de entrada hacia server prometheus [9100]
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        source: "{{ server_ip }}" 
        destination: "{{ item }}"
        destination_port: 9100  
        ctstate: NEW,ESTABLISHED,RELATED
        jump: ACCEPT
        action: insert
        rule_num: 2  
      become: true
      with_items:
        - 172.16.8.64
      when: iptables_status.rc == 0 and ansible_distribution_major_version == '6'

    - name: Guardo reglas
      command: service iptables save
      become: true
      when: iptables_status.rc == 0 and ansible_distribution_major_version == '6'

    - name: Create directory for node_exporter
      file:
        path: "{{ node_exporter_install_dir }}"
        state: directory
        mode: "0755"
        
    - name: Copio Node exporter
      copy:
        src: "/tecnol/ansible/olam/playbooks/node-exporter/node_exporter-1.7.0.linux-amd64.tar.gz"
        dest: "/tmp/node_exporter/"
        mode: '0644'

    - name: Extraigo 
      unarchive:
        src: "/tmp/node_exporter/node_exporter-1.7.0.linux-amd64.tar.gz"
        dest: "{{ node_exporter_install_dir }}"
        remote_src: yes
        extra_opts: --strip-components=1

    - name: Genero el servicio [rhel6]
      template:
        src: "node_exporter_6.service.j2"
        dest: "/etc/init.d/node_exporter.service"
      when: ansible_distribution_major_version == '6'

    - name: Add service to chkconfig on CentOS 6
      command: chkconfig --add node_exporter.service
      when: ansible_distribution_major_version == '6'

    - name: Ensure service starts on boot
      command: chkconfig node_exporter.service on
      when: ansible_distribution_major_version == '6'

    - name: Cambio permisos al servicio
      command: chmod 755 /etc/init.d/node_exporter.service
      when:  ansible_distribution_major_version == '6'

    - name: Inicio el servicio
      service:
        name: node_exporter.service
        state: started
        
    - name: Genero el servicio [rhel7]
      template:
        src: "node_exporter_7.service.j2"
        dest: "/etc/systemd/system/node_exporter.service"
      when: ansible_distribution_major_version == '7' or ansible_distribution_major_version == '8' or ansible_distribution_major_version == '9'
    
    - name: Add service to systemd on RHEL 7
      systemd:
        name: node_exporter.service
        enabled: yes
      when: ansible_distribution_major_version == '7' or ansible_distribution_major_version == '8' or ansible_distribution_major_version == '9'
      
    - name: Inicio el servicio
      service:
        name: node_exporter.service
        state: started
        enabled: yes
      when: ansible_distribution_major_version == '7' or ansible_distribution_major_version == '8' or ansible_distribution_major_version == '9'
