---
- name: Abrir puertos
  hosts: all
  become: true   

  vars:
         ansible_python_interpreter: /usr/bin/python3.9

  tasks:

    - name: Backup rules
      shell: iptables-save > /etc/sysconfig/iptables.{{ ansible_date_time.date }}
      args:
        warn: no
      register: iptables_backup
      changed_when: iptables_backup.stdout != ""

    - name: Obtener IP server
      set_fact:
        server_ip: "{{ ansible_default_ipv4.address }}"

    - name: Agrego reglas de entrada [55249]
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        source: "{{ item }}"
        destination: "{{ server_ip }}"
        destination_port: 55249  
        ctstate: NEW,ESTABLISHED,RELATED
        jump: ACCEPT
        action: insert
        rule_num: 10   ##Inserto regla después de la linea 10 de la cadena INPUT
      become: true
      with_items:
        - 172.16.8.71
        - 172.16.8.72

    - name: Agrego reglas de entrada [55246]
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        source: 172.16.8.70
        destination: "{{ server_ip }}"
        source_port: 55246  
        ctstate: NEW,ESTABLISHED,RELATED
        jump: ACCEPT
        action: insert
        rule_num: 5  ##Inserto regla después de la linea 9 de la cadena OUTPUT
      become: true

    - name: Guardo reglas
      command: service iptables save
      become: true
